M48
; DRILL file {KiCad 8.0.1} date 2026-07-01T21:36:18+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-01T21:36:18+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C4.000
%
G90
G05
T1
X124.92Y-177.5
X135.08Y-177.5
T2
X92.5Y-90.0
X92.5Y-101.43
T3
X86.15Y-92.13
T4
X86.0Y-66.0
X86.0Y-186.0
X174.0Y-66.0
X174.0Y-186.0
T5
X130.0Y-177.5
M30
